<?php

return [
    'index'   =>[ 'index/index/index',['ext'=>'html']],
    'admin'  => ['admin/admin/admin',['ext'=>'html']],
    'welcome' => ['admin/admin/welcome',['ext'=>'html']],
    'admin_role' =>['admin/users/admin_role',['ext'=>'html']],
    'admin_role_add' =>['admin/users/admin_role_add',['ext'=>'html']],
    'role_insert' =>['admin/users/role_insert',['ext'=>'html']],
    'add_insert' =>['admin/users/add_insert',['ext'=>'html']],
    'auth_insert' =>['admin/users/auth_insert',['ext'=>'html']],
    'auth_upload' =>['admin/users/auth_upload',['ext'=>'html']],
    'admin_add' =>['admin/users/admin_add',['ext'=>'html']],
    'admin_list' =>['admin/users/admin_list',['ext'=>'html']],
    'admin_static' =>['admin/users/admin_static',['ext'=>'html']],
    'admin_auth' =>['admin/users/admin_auth',['ext'=>'html']],
    'role_update' =>['admin/users/role_update',['ext'=>'html']],
    'admin_auth_upload' =>['admin/users/admin_auth_upload',['ext'=>'html']],
    'auth_del' =>['admin/users/auth_del',['ext'=>'html'],],
    'admin_auth_one' =>['admin/users/admin_auth_one',['ext'=>'html']],
    'admin_auth_two' =>['admin/users/admin_auth_two',['ext'=>'html']],
    'admin_auth_there' =>['admin/users/admin_auth_there',['ext'=>'html']],
    'role_update_add' =>['admin/users/role_update_add',['ext'=>'html']],
    'role_del' =>['admin/users/role_del',['ext'=>'html']],
    'index_login' =>['admin/login/login',['ext'=>'html']],
    'do_login' =>['admin/login/do_login',['ext'=>'html']],
    'admin_insert' =>['admin/users/admin_insert',['ext'=>'html']],
    'admin_edit' =>['admin/users/admin_edit',['ext'=>'html']],
    'admin_del' =>['admin/users/admin_del',['ext'=>'html']],
    'login_del' =>['admin/login/login_del',['ext'=>'html']],
    'develop'=>['index/develop/develop',['ext'=>'html']],
    'develop_list'=>['index/develop/develop_list',['ext'=>'html']],
    'develop_support_ajax'=>['index/develop/develop_support_ajax',['ext'=>'html']],
    'develop_comment_ajax'=>['index/develop/develop_comment_ajax',['ext'=>'html']],
    'develop_comments_ajax'=>['index/develop/develop_comments_ajax',['ext'=>'html']],
    'develop_user_support_ajax'=>['index/develop/develop_user_support_ajax',['ext'=>'html']],
    'system_module' =>['admin/system/system_module',['ext'=>'html']],
    'system_money' =>['admin/system/system_money',['ext'=>'html']],
    'system_capital' =>['admin/system/system_capital',['ext'=>'html']],
    'system_money_add' =>['admin/system/system_money_add',['ext'=>'html']],
    'system_capital_add' =>['admin/system/system_capital_add',['ext'=>'html']],
    'system_money_static' =>['admin/system/system_money_static',['ext'=>'html']],
    'system_capital_static' =>['admin/system/system_capital_static',['ext'=>'html']],
    'system_money_form' =>['admin/system/system_money_form',['ext'=>'html']],
    'system_capital_form' =>['admin/system/system_capital_form',['ext'=>'html']],
    'system_money_update' =>['admin/system/system_money_update',['ext'=>'html']],
    'money_update' =>['admin/system/money_update',['ext'=>'html']],
    'system_money_del' =>['admin/system/system_money_del',['ext'=>'html']],
    'system_capital_del' =>['admin/system/system_capital_del',['ext'=>'html']],
    'system_module_add' =>['admin/system/system_module_add',['ext'=>'html']],
    'system_module_form' =>['admin/system/system_module_form',['ext'=>'html']],
    'system_module_update' =>['admin/system/system_module_update',['ext'=>'html']],
    'module_update' =>['admin/system/module_update',['ext'=>'html']],
    'module_del' =>['admin/system/module_del',['ext'=>'html']],
    'collection'=>['index/comment/collection',['ext'=>'html']],
    'follow'=>['index/comment/follow',['ext'=>'html']],
    'collection_list'=>['index/comment/collection_list',['ext'=>'html']],
    'article_list' =>['admin/article/article_list',['ext'=>'html']],
    'article_add' =>['admin/article/article_add',['ext'=>'html']],
    'article_form' =>['admin/article/article_form',['ext'=>'html']],
    'article_updata' =>['admin/article/article_updata',['ext'=>'html']],
    'article_status' =>['admin/article/article_status',['ext'=>'html']],
    'updata_article' =>['admin/article/updata_article',['ext'=>'html']],
    'article_del' =>['admin/article/article_del',['ext'=>'html']],
    'column_list' =>['admin/article/column_list',['ext'=>'html']],
    'type_list' =>['admin/article/type_list',['ext'=>'html']],
    'type_add' =>['admin/article/type_add',['ext'=>'html']],
    'column_add' =>['admin/article/column_add',['ext'=>'html']],
    'column_form' =>['admin/article/column_form',['ext'=>'html']],
    'type_form' =>['admin/article/type_form',['ext'=>'html']],
    'column_updata' =>['admin/article/column_updata',['ext'=>'html']],
    'updata_column' =>['admin/article/updata_column',['ext'=>'html']],
    'column_del' =>['admin/article/column_del',['ext'=>'html']],
    'type_updata' =>['admin/article/type_updata',['ext'=>'html']],
    'updata_type' =>['admin/article/updata_type',['ext'=>'html']],
    'type_del' =>['admin/article/type_del',['ext'=>'html']],
    'comment_list' =>['admin/comment/comment_list',['ext'=>'html']],
    'comment_status' =>['admin/comment/comment_status',['ext'=>'html']],
    'comment_del' =>['admin/comment/comment_del',['ext'=>'html']],
    'comment_recovery' =>['admin/comment/comment_recovery',['ext'=>'html']],
    'comment_recovery_insert' =>['admin/comment/comment_recovery_insert',['ext'=>'html']],
    'comment_recovery_del' =>['admin/comment/comment_recovery_del',['ext'=>'html']],
    'member_list' =>['admin/member/member_list',['ext'=>'html']],
    'member_del' =>['admin/member/member_del',['ext'=>'html']],
    'member_del_del' =>['admin/member/member_del_del',['ext'=>'html']],
    'member_add' =>['admin/member/member_add',['ext'=>'html']],
    'member_static' =>['admin/member/member_static',['ext'=>'html']],
    'member_show' =>['admin/member/member_show',['ext'=>'html']],
    'member_up' =>['admin/member/member_up',['ext'=>'html']],
    'member_updata' =>['admin/member/member_updata',['ext'=>'html']],
    'member_upda' =>['admin/member/member_upda',['ext'=>'html']],
    'member_level' =>['admin/member/member_level',['ext'=>'html']],
    'member_del_restore' =>['admin/member/member_del_restore',['ext'=>'html']],
    'member_del_date' =>['admin/member/member_del_date',['ext'=>'html']],
    'admin_sign' =>['admin/member/member_sign',['ext'=>'html']],
    'member_coin' =>['admin/member/member_coin',['ext'=>'html']],
    'coin_del' =>['admin/member/coin_del',['ext'=>'html']],
    'url/:id' =>['index/url/url',['']],
    'level_add' =>['admin/member/level_add',['ext'=>'html']],
    'level_up' =>['admin/member/level_up',['ext'=>'html']],
    'level_updata' =>['admin/member/level_updata',['ext'=>'html']],
    'level_upda' =>['admin/member/level_upda',['ext'=>'html']],
    'level_del' =>['admin/member/level_del',['ext'=>'html']],
    'member_integral' =>['admin/member/member_integral',['ext'=>'html']],
    'integral_add' =>['admin/member/integral_add',['ext'=>'html']],
    'integral_up' =>['admin/member/integral_up',['ext'=>'html']],
    'integral_updata' =>['admin/member/integral_updata',['ext'=>'html']],
    'integral_upda' =>['admin/member/integral_upda',['ext'=>'html']],
    'integral_del' =>['admin/member/integral_del',['ext'=>'html']],
    'love_month_list' =>['admin/love/love_month_list',['ext'=>'html']],
    'love_month_add' =>['admin/love/love_month_add',['ext'=>'html']],
    'love_month_update' =>['admin/love/love_month_update',['ext'=>'html']],
    'love_month_del' =>['admin/love/love_month_del',['ext'=>'html']],
    'love_month_form' =>['admin/love/love_month_form',['ext'=>'html']],
    'update_love_month' =>['admin/love/update_love_month',['ext'=>'html']],
    'love_week_list' =>['admin/love/love_week_list',['ext'=>'html']],
    'love_week_add' =>['admin/love/love_week_add',['ext'=>'html']],
    'love_week_update' =>['admin/love/love_week_update',['ext'=>'html']],
    'love_week_del' =>['admin/love/love_week_del',['ext'=>'html']],
    'love_week_form' =>['admin/love/love_week_form',['ext'=>'html']],
    'update_love_week' =>['admin/love/update_love_week',['ext'=>'html']],
    'love_video_list' =>['admin/love/love_video_list',['ext'=>'html']],
    'love_video_add' =>['admin/love/love_video_add',['ext'=>'html']],
    'love_video_update' =>['admin/love/love_video_update',['ext'=>'html']],
    'love_video_del' =>['admin/love/love_video_del',['ext'=>'html']],
    'love_video_form' =>['admin/love/love_video_form',['ext'=>'html']],
    'update_love_video' =>['admin/love/update_love_video',['ext'=>'html']],
    'level_record_list' =>['admin/level/level_record_list',['ext'=>'html']],
    'level_record_add' =>['admin/level/level_record_add',['ext'=>'html']],
    'level_record_update' =>['admin/level/level_record_update',['ext'=>'html']],
    'level_record_del' =>['admin/level/level_record_del',['ext'=>'html']],
    'level_record_form' =>['admin/level/level_record_form',['ext'=>'html']],
    'update_level_record' =>['admin/level/update_level_record',['ext'=>'html']],
    'level_class_list' =>['admin/level/level_class_list',['ext'=>'html']],
    'level_class_add' =>['admin/level/level_class_add',['ext'=>'html']],
    'level_class_update' =>['admin/level/level_class_update',['ext'=>'html']],
    'level_class_del' =>['admin/level/level_class_del',['ext'=>'html']],
    'level_class_form' =>['admin/level/level_class_form',['ext'=>'html']],
    'update_level_class' =>['admin/level/update_level_class',['ext'=>'html']],
    'level_date_list' =>['admin/level/level_date_list',['ext'=>'html']],
    'level_date_add' =>['admin/level/level_date_add',['ext'=>'html']],
    'level_date_update' =>['admin/level/level_date_update',['ext'=>'html']],
    'level_date_del' =>['admin/level/level_date_del',['ext'=>'html']],
    'level_date_form' =>['admin/level/level_date_form',['ext'=>'html']],
    'update_level_date' =>['admin/level/update_level_date',['ext'=>'html']],
    'level_number_list' =>['admin/level/level_number_list',['ext'=>'html']],
    'level_number_add' =>['admin/level/level_number_add',['ext'=>'html']],
    'level_number_update' =>['admin/level/level_number_update',['ext'=>'html']],
    'level_number_del' =>['admin/level/level_number_del',['ext'=>'html']],
    'level_number_form' =>['admin/level/level_number_form',['ext'=>'html']],
    'update_level_number' =>['admin/level/update_level_number',['ext'=>'html']],
    'level_require_list' =>['admin/level/level_require_list',['ext'=>'html']],
    'level_require_add' =>['admin/level/level_require_add',['ext'=>'html']],
    'level_require_update' =>['admin/level/level_require_update',['ext'=>'html']],
    'level_require_del' =>['admin/level/level_require_del',['ext'=>'html']],
    'level_require_form' =>['admin/level/level_require_form',['ext'=>'html']],
    'update_level_require' =>['admin/level/update_level_require',['ext'=>'html']],
    'level_tutor_list' =>['admin/level/level_tutor_list',['ext'=>'html']],
    'level_tutor_add' =>['admin/level/level_tutor_add',['ext'=>'html']],
    'level_tutor_update' =>['admin/level/level_tutor_update',['ext'=>'html']],
    'level_tutor_del' =>['admin/level/level_tutor_del',['ext'=>'html']],
    'level_tutor_form' =>['admin/level/level_tutor_form',['ext'=>'html']],
    'update_level_tutor' =>['admin/level/update_level_tutor',['ext'=>'html']],
    'level_tutor_del_list' =>['admin/level/level_tutor_del_list',['ext'=>'html']],
    'level_tutor_del_update' =>['admin/level/level_tutor_del_update',['ext'=>'html']],
    'level_tutor_del_del' =>['admin/level/level_tutor_del_del',['ext'=>'html']],
    'level_tutor_del_form' =>['admin/level/level_tutor_del_form',['ext'=>'html']],
    'update_level_tutor_del' =>['admin/level/update_level_tutor_del',['ext'=>'html']],
    'taobao_list' =>['admin/taobao/taobao_list',['ext'=>'html']],
    'taobao_update' =>['admin/taobao/taobao_update',['ext'=>'html']],
    'taobao_del' =>['admin/taobao/taobao_del',['ext'=>'html']],
    'taobao_form' =>['admin/taobao/taobao_form',['ext'=>'html']],
    'update_taobao' =>['admin/taobao/update_taobao',['ext'=>'html']],
    'admin_develop_text'=>['admin/develop/admin_develop_text',['ext'=>'html']],
    'admin_develop_add'=>['admin/develop/admin_develop_add',['ext'=>'html']],
    'admin_develop_edit'=>['admin/develop/admin_develop_edit',['ext'=>'html']],
    'admin_develop_form'=>['admin/develop/admin_develop_form',['ext'=>'html']],
    'admin_develop_update'=>['admin/develop/admin_develop_update',['ext'=>'html']],
    'admin_develop_del'=>['admin/develop/admin_develop_del',['ext'=>'html']],
    'admin_develop_central'=>['admin/develop/admin_develop_central',['ext'=>'html']],
    'admin_develop_function'=>['admin/develop/admin_develop_function',['ext'=>'html']],
    'admin_develop_support'=>['admin/develop/admin_develop_support',['ext'=>'html']],
    'admin_develop_texts'=>['admin/develop/admin_develop_texts',['ext'=>'html']],
    'admin_develop_comment'=>['admin/develop/admin_develop_comment',['ext'=>'html']],
    'admin_theme_copy_list'=>['admin/mange/admin_theme_copy_list',['ext'=>'html']],
    'mange_theme_copy_del'=>['admin/mange/mange_theme_copy_del',['ext'=>'html']],
    'mange_theme_copy_static'=>['admin/mange/mange_theme_copy_static',['ext'=>'html']],
    'admin_theme_list'=>['admin/mange/admin_theme_list',['ext'=>'html']],
    'mange_theme_del'=>['admin/mange/mange_theme_del',['ext'=>'html']],
    'mange_theme_static'=>['admin/mange/mange_theme_static',['ext'=>'html']],
    'admin_part_copy_list'=>['admin/mange/admin_part_copy_list',['ext'=>'html']],
    'mange_part_copy_del'=>['admin/mange/mange_part_copy_del',['ext'=>'html']],
    'mange_part_copy_static'=>['admin/mange/mange_part_copy_static',['ext'=>'html']],
    'admin_part_list'=>['admin/mange/admin_part_list',['ext'=>'html']],
    'mange_part_del'=>['admin/mange/mange_part_del',['ext'=>'html']],
    'mange_part_static'=>['admin/mange/mange_part_static',['ext'=>'html']],
    'login' =>['index/login/login',['ext'=>'html']],
    'retrieve' =>['index/login/retrieve',['ext'=>'html']],
    'retrieve_email' =>['index/login/retrieve_email',['ext'=>'html']],
    'login_up' =>['index/login/login_up',['ext'=>'html']],
    'login_upd' =>['index/login/login_upd',['ext'=>'html']],
    'register' =>['index/login/register',['ext'=>'html']],
    'users/:uid' =>['index/user/users',['']],
    'fans/:id' =>['index/user/fans',['']],
    'total' =>['index/total/total',['ext'=>'html']],
    'total_week' =>['index/total/total_week',['ext'=>'html']],
    'Follow' =>['index/user/Follow',['ext'=>'html']],
    'Videos/:uid' =>['index/user/Videos',['']],
    'theme_list/:uid' =>['index/user/theme_list',['']],
    'fans_insert' =>['index/user/fans_insert',['ext'=>'html']],
    'user_kidney' =>['index/user/user_kidney',['ext'=>'html']],
    'user_notice' =>['index/user/user_notice',['ext'=>'html']],
    'collect/:id' =>['index/user/collect',['']],
    'collect_list' =>['index/user/collect_list',['ext'=>'html']],
    'collect_list_delete' =>['index/user/collect_list_delete',['ext'=>'html']],
    'collect_static' =>['index/user/collect_static',['ext'=>'html']],
    'collect_static_name' =>['index/user/collect_static_name',['ext'=>'html']],
    'collect_static_power' =>['index/user/collect_static_power',['ext'=>'html']],
    'collect_static_delete' =>['index/user/collect_static_delete',['ext'=>'html']],
    'fans_del' =>['index/user/fans_del',['ext'=>'html']],
    'user_form' =>['index/user/user_form',['ext'=>'html']],
    'cy_upload' =>['index/upload/cy_upload',['ext'=>'html']],
    'cy_insert' =>['index/upload/cy_insert',['ext'=>'html']],
    'manga_list' =>['admin/goods/manga_list',['ext'=>'html']],
    'manga_two_list' =>['admin/goods/manga_two_list',['ext'=>'html']],
    'manga_new_list' =>['admin/goods/manga_new_list',['ext'=>'html']],
    'mange_list' =>['admin/goods/mange_list',['ext'=>'html']],
    'manga_show' =>['admin/goods/manga_show',['ext'=>'html']],
    'manga_new_show' =>['admin/goods/manga_new_show',['ext'=>'html']],
    'manga_collect_show' =>['admin/goods/manga_collect_show',['ext'=>'html']],
    'manga_del' =>['admin/goods/manga_del',['ext'=>'html']],
    'manga_new_del' =>['admin/goods/manga_new_del',['ext'=>'html']],
    'manga_two_del' =>['admin/goods/manga_two_del',['ext'=>'html']],
    'manga_collects_del' =>['admin/goods/manga_collects_del',['ext'=>'html']],
    'manga_collects_list' =>['admin/goods/manga_collects_list',['ext'=>'html']],
    'manga_new_static' =>['admin/goods/manga_new_static',['ext'=>'html']],
    'manges_static' =>['admin/goods/manges_static',['ext'=>'html']],
    'manga_two_static' =>['admin/goods/manga_two_static',['ext'=>'html']],
    'search' =>['index/index/search',['ext'=>'html']],
    'search_videos' =>['index/user/search_videos',['ext'=>'html']],
    'searchs' =>['index/index/searchs',['ext'=>'html']],
    'register_user' =>['index/login/register_user',['ext'=>'html']],
    'register_email' =>['index/login/register_email',['ext'=>'html']],
    'play/:play' =>['index/video/play',['']],
    'main/:main' =>['index/special/mange',['']],
    'theme/:theme' =>['index/theme/theme',['']],
    'graded/:graded' =>['index/theme/graded',['']],
    'sustain/:sustain' =>['index/theme/sustain',['']],
    'award/:award'=>['index/theme/award',['']],
    'attention/:attention'=>['index/theme/attention',['']],
    'video/:video' =>['index/theme/video',['']],
    'assess/:assess' =>['index/special/assess',['']],
    'support/:support' =>['index/special/support',['']],
    'mange_assess' =>['index/special/mange_assess',['ext'=>'html']],
    'theme_num_li' =>['index/theme/theme_num_li',['ext'=>'html']],
    'special_num_li' =>['index/special/special_num_li',['ext'=>'html']],
    'core' =>['index/core/core',['ext'=>'html']],
    'honor/:honor'=>['index/special/honor',['']],
    'honors/:honor'=>['index/special/honors',['']],
    'just/:just'=>['index/special/just',['']],
    'mange_collect_list'=>['index/theme/mange_collect_list',['ext'=>'html']],
    'mange_collect_new'=>['index/theme/mange_collect_new',['ext'=>'html']],
    'level_list/:level_list'=>['index/user/level_list',['']],
    'member_level_upd'=>['index/user/member_level_upd',['ext'=>'html']],
    'create'=>['index/create/create',['ext'=>'html']],
    'member_level_up'=>['index/user/member_level_up',['ext'=>'html']],
    'member_level_rise'=>['index/user/member_level_rise',['ext'=>'html']],
    'article_list/:article'=>['index/article/article_list',['']],
    'articles_list/:articles'=>['index/article/articles_list',['']],
    'essay_list/:article'=>['index/article/essay_list',['']],
    'essays_list/:articles'=>['index/article/essays_list',['']],
    'special_coin' =>['index/special/special_coin',['ext'=>'html']],
    'mange_collect' =>['index/theme/mange_collect',['ext'=>'html']],
    'mange_collect_del' =>['index/theme/mange_collect_del',['ext'=>'html']],
    'mange_offer' =>['index/theme/mange_offer',['ext'=>'html']],
    'mange_comment' =>['index/theme/mange_comment',['ext'=>'html']],
    'mange_ajax_comment' =>['index/theme/mange_ajax_comment',['ext'=>'html']],
    'support_ajax' =>['index/theme/support_ajax',['ext'=>'html']],
    'mange_support' =>['index/theme/mange_support',['ext'=>'html']],
    'just_insert' =>['index/theme/just_insert',['ext'=>'html']],
    'just_del' =>['index/theme/just_del',['ext'=>'html']],
    'contribute'=>['index/contribute/contribute',['ext'=>'html']],
    'theme'=>['index/contribute/theme',['ext'=>'html']],
    'theme_post'=>['index/contribute/theme_post',['ext'=>'html']],
    'works_theme_form'=>['index/contribute/works_theme_form',['ext'=>'html']],
    'works'=>['index/contribute/works',['ext'=>'html']],
    'works_post'=>['index/contribute/works_post',['ext'=>'html']],
    'contribution'=>['index/contribute/contribution',['ext'=>'html']],
    'mangacb'=>['index/contribute/mangacb',['ext'=>'html']],
    'articlecb/:article'=>['index/contribute/articlecb',['']],
    'manga_conform'=>['index/contribute/manga_conform',['ext'=>'html']],
    'works_form'=>['index/contribute/works_form',['ext'=>'html']],
    'works_collect_form'=>['index/contribute/works_collect_form',['ext'=>'html']],
    'article_conform'=>['index/contribute/article_conform',['ext'=>'html']],
    'articleCb_post'=>['index/contribute/articleCb_post',['ext'=>'html']],
    'mangaCb_post'=>['index/contribute/mangaCb_post',['ext'=>'html']],
    'login_quit'=>['index/login/login_quit',['ext'=>'html']],
    'login_pass'=>['index/login/login_pass',['ext'=>'html']],
    'email_list'=>['admin/website/email_list',['ext'=>'html']],
    'email_form'=>['admin/website/email_form',['ext'=>'html']],
    'upload_list' =>['admin/website/upload_list',['ext'=>'html']],
    'upload_form' =>['admin/website/upload_form',['ext'=>'html']],
    'site_list'=>['admin/website/site_list',['ext'=>'html']],
    'site_form'=>['admin/website/site_form',['ext'=>'html']],
    'register_list'=>['admin/website/register_list',['ext'=>'html']],
    'register_form'=>['admin/website/register_form',['ext'=>'html']],
    'optimize_list'=>['admin/website/optimize_list',['ext'=>'html']],
    'optimize_form'=>['admin/website/optimize_form',['ext'=>'html']],
    'seo_list'=>['admin/website/seo_list',['ext'=>'html']],
    'seo_form'=>['admin/website/seo_form',['ext'=>'html']],
    'domain_list'=>['admin/website/domain_list',['ext'=>'html']],
    'domain_form'=>['admin/website/domain_form',['ext'=>'html']],
    'users_list'=>['admin/website/users_list',['ext'=>'html']],
    'users_form'=>['admin/website/users_form',['ext'=>'html']],
    'search_s_list'=>['admin/website/search_s_list',['ext'=>'html']],
    'search_s_form'=>['admin/website/search_s_form',['ext'=>'html']],
    'email_activate'=>['index/login/email_activate',['ext'=>'html']],
    'lists'=>['index/video/lists',['']],
    'ranking'=>['index/ranking/ranking',['ext'=>'html']],
    'nav'=>['admin/nav/nav',['ext'=>'html']],
    'nav_add'=>['admin/nav/nav_add',['ext'=>'html']],
    'nav_form'=>['admin/nav/nav_form',['ext'=>'html']],
    'nav_single'=>['admin/nav/nav_single',['ext'=>'html']],
    'nav_total'=>['admin/nav/nav_total',['ext'=>'html']],
    'nav_vo'=>['admin/nav/nav_vo',['ext'=>'html']],
    'nav_nav'=>['admin/nav/nav_nav',['ext'=>'html']],
    'nav_del'=>['admin/nav/nav_del',['ext'=>'html']],
    'nav_edit'=>['admin/nav/nav_edit',['ext'=>'html']],
    'nav_edit_form'=>['admin/nav/nav_edit_form',['ext'=>'html']],
    'contribute_total'=>['index/contribute/contribute_total',['ext'=>'html']],
    'contribute_form'=>['index/contribute/contribute_form',['ext'=>'html']],
    'user_email'=>['index/user/user_email',['ext'=>'html']],
    'password_activate'=>['index/user/password_activate',['ext'=>'html']],
    'password_form'=>['index/user/password_form',['ext'=>'html']],
    'activation_email'=>['index/user/activation_email',['ext'=>'html']],
    'email_send'=>['index/user/email_send',['ext'=>'html']],
    'upload_logo'=>['index/user/upload_logo',['ext'=>'html']],
    'sign'=>['index/sign/sign',['ext'=>'html']],
    'sign_up'=>['index/sign/sign_up',['ext'=>'html']],
    'help_classify'=>['admin/help/help_classify',['ext'=>'html']],
    'help_content'=>['admin/help/help_content',['ext'=>'html']],
    'help_classify_add'=>['admin/help/help_classify_add',['ext'=>'html']],
    'help_content_add'=>['admin/help/help_content_add',['ext'=>'html']],
    'help_classify_edit'=>['admin/help/help_classify_edit',['ext'=>'html']],
    'help_content_edit'=>['admin/help/help_content_edit',['ext'=>'html']],
    'help_classify_del'=>['admin/help/help_classify_del',['ext'=>'html']],
    'help_content_del'=>['admin/help/help_content_del',['ext'=>'html']],
    'help_classify_form'=>['admin/help/help_classify_form',['ext'=>'html']],
    'help_content_form'=>['admin/help/help_content_form',['ext'=>'html']],
    'help'=>['index/help/help',['ext'=>'html']],
    'help_ajax'=>['index/help/help_ajax',['ext'=>'html']],
    'help_list_ajax'=>['index/help/help_list_ajax',['ext'=>'html']],
    'user_new'=>['index/news/user_new',['ext'=>'html']],
    'droit'=>['index/droit/droit',['ext'=>'html']],
    'rise'=>['index/rise/rise',['ext'=>'html']],
    'rise/:rise'=>['index/rise/rises',['']],
    'rise_list'=>['index/rise/rise_list',['ext'=>'html']],
    'rise_money'=>['index/rise/rise_money',['ext'=>'html']],
    'rise_text'=>['index/rise/rise_text',['ext'=>'html']],
    'rise_fans_become'=>['index/rise/rise_fans_become',['ext'=>'html']],
    'rise_support_become'=>['index/rise/rise_support_become',['ext'=>'html']],
    'rise_comment'=>['index/rise/rise_comment',['ext'=>'html']],
    'level_power'=>['index/rise/level_power',['ext'=>'html']],
    'droit_static'=>['index/droit/droit_static',['ext'=>'html']],
    'user_ajax'=>['index/news/user_ajax',['ext'=>'html']],
    'home/:nav'=>['index/index/home',['ext'=>'html']],
    'mysql'=>['admin/sql/mysql',['ext'=>'html']],
    'terms_list'=>['admin/content/terms_list',['ext'=>'html']],
    'terms_form'=>['admin/content/terms_form',['ext'=>'html']],
    'report_list'=>['admin/content/report_list',['ext'=>'html']],
    'report_static'=>['admin/content/report_static',['ext'=>'html']],
    'report_del'=>['admin/content/report_del',['ext'=>'html']],
    'handle_del'=>['admin/content/handle_del',['ext'=>'html']],
    'report_handle'=>['admin/content/report_handle',['ext'=>'html']],
    'video_report'=>['index/help/video_report',['ext'=>'html']],
    'push_list'=>['admin/manage/push_list',['ext'=>'html']],
    'push_add'=>['admin/manage/push_add',['ext'=>'html']],
    'pushs_add'=>['admin/manage/pushs_add',['ext'=>'html']],
    'push_form'=>['admin/manage/push_form',['ext'=>'html']],
    'push_edit'=>['admin/manage/push_edit',['ext'=>'html']],
    'push_forms'=>['admin/manage/push_forms',['ext'=>'html']],
    'pushs_form'=>['admin/manage/pushs_form',['ext'=>'html']],
    'push_ajax'=>['admin/manage/push_ajax',['ext'=>'html']],
    'pushs_del'=>['admin/manage/pushs_del',['ext'=>'html']],
    'push_del'=>['admin/manage/push_del',['ext'=>'html']],
    'pushs_ajax'=>['admin/manage/pushs_ajax',['ext'=>'html']],
    'pushs_list'=>['admin/manage/pushs_list',['ext'=>'html']],
    'guide_list'=>['admin/manage/guide_list',['ext'=>'html']],
    'guide_add'=>['admin/manage/guide_add',['ext'=>'html']],
    'guides_add'=>['admin/manage/guides_add',['ext'=>'html']],
    'guide_form'=>['admin/manage/guide_form',['ext'=>'html']],
    'guide_edit'=>['admin/manage/guide_edit',['ext'=>'html']],
    'guide_forms'=>['admin/manage/guide_forms',['ext'=>'html']],
    'guides_form'=>['admin/manage/guides_form',['ext'=>'html']],
    'guide_ajax'=>['admin/manage/guide_ajax',['ext'=>'html']],
    'guides_del'=>['admin/manage/guides_del',['ext'=>'html']],
    'guide_del'=>['admin/manage/guide_del',['ext'=>'html']],
    'guides_ajax'=>['admin/manage/guides_ajax',['ext'=>'html']],
    'guides_list'=>['admin/manage/guides_list',['ext'=>'html']],
    'admins'=>['index/admins/admins',['ext'=>'html']],
    'welcomes'=>['index/admins/welcomes',['ext'=>'html']],
    'front_login'=>['index/admins/front_login',['ext'=>'html']],
    'front_login_del'=>['index/admins/front_login_del',['ext'=>'html']],
    'front_do_login'=>['index/admins/front_do_login',['ext'=>'html']],
    'admins_video'=>['index/admins/admins_video',['ext'=>'html']],
    'admins_video_collects'=>['index/admins/admins_video_collects',['ext'=>'html']],
    'admins_video_static'=>['index/admins/admins_video_static',['ext'=>'html']],
    'admins_video_comment'=>['index/admins/admins_video_comment',['ext'=>'html']],
    'front_list'=>['admin/front/front_list',['ext'=>'html']],
    'system_front_add'=>['admin/front/system_front_add',['ext'=>'html']],
    'system_front_from'=>['admin/front/system_front_from',['ext'=>'html']],
    'system_front_update'=>['admin/front/system_front_update',['ext'=>'html']],
    'front_update'=>['admin/front/front_update',['ext'=>'html']],
    'front_del'=>['admin/front/front_del',['ext'=>'html']],
    'front_power'=>['admin/front/front_power',['ext'=>'html']],
    'front_power_add'=>['admin/front/front_power_add',['ext'=>'html']],
    'front_auth'=>['admin/front/front_auth',['ext'=>'html']],
    'front_auth_one' =>['admin/front/front_auth_one',['ext'=>'html']],
    'front_auth_two' =>['admin/front/front_auth_two',['ext'=>'html']],
    'front_auth_there' =>['admin/front/front_auth_there',['ext'=>'html']],
    'front_auth_insert' =>['admin/front/front_auth_insert',['ext'=>'html']],
    'front_auth_upload' =>['admin/front/front_auth_upload',['ext'=>'html']],
    'front_auth_del' =>['admin/front/front_auth_del',['ext'=>'html']],
    'auth_front_upload' =>['admin/front/auth_front_upload',['ext'=>'html']],
    'front_role' =>['admin/front/front_role',['ext'=>'html']],
    'front_role_add' =>['admin/front/front_role_add',['ext'=>'html']],
    'front_role_insert' =>['admin/front/front_role_insert',['ext'=>'html']],
    'front_role_update' =>['admin/front/front_role_update',['ext'=>'html']],
    'front_role_update_add' =>['admin/front/front_role_update_add',['ext'=>'html']],
    'front_role_del' =>['admin/front/front_role_del',['ext'=>'html']],
    'front_member' =>['admin/front/front_member',['ext'=>'html']],
    'front_insert' =>['admin/front/front_insert',['ext'=>'html']],
    'front_power_del' =>['admin/front/front_power_del',['ext'=>'html']],
    'front_power_edit' =>['admin/front/front_power_edit',['ext'=>'html']],
    'front_power_static' =>['admin/front/front_power_static',['ext'=>'html']],
    'front_power_update' =>['admin/front/front_power_update',['ext'=>'html']],
    'article' =>['index/help/article',['ext'=>'html']],
    'articles/:id' =>['index/help/articles',['']],
    'tutor' =>['index/taobao/tutor',['ext'=>'html']],
    'taobao' =>['index/taobao/taobao',['ext'=>'html']],
    'level/:level' =>['index/level/level',['']],
    'grow/:grow' =>['index/level/grow',['']],
    'level_open' =>['index/level/level_open',['ext'=>'html']],
    'level_form' =>['index/level/level_form',['ext'=>'html']],
    'level_dan' =>['index/level/level_dan',['ext'=>'html']],
    'level_zhi' =>['index/level/level_zhi',['ext'=>'html']],
    'level_zhiding' =>['index/level/level_zhiding',['ext'=>'html']],
    'level_upd' =>['index/level/level_upd',['ext'=>'html']],
    'sitemap' =>['index/sitemap/sitemap',['ext'=>'xml']],
    'sitemap1' =>['index/sitemap/sitemap1',['ext'=>'xml']],
    'tor/:tor' =>['index/taobao/tor',['']],

    'api_login' =>['index/api/login',['ext'=>'html']],
    'book' =>['index/api/book',['ext'=>'html']],
    'book_word' =>['index/api/book_word',['ext'=>'html']],
    'book_delete' =>['index/api/book_delete',['ext'=>'html']],
    'book_search' =>['index/api/book_search',['ext'=>'html']],
    'book_tag' =>['index/api/book_tag',['ext'=>'html']],
    'book_hint' =>['index/api/book_hint',['ext'=>'html']],
    'book_list' =>['index/api/book_list',['ext'=>'html']],
    'book_item' =>['index/api/book_item',['ext'=>'html']],
    'register_code' =>['index/api/register_code',['ext'=>'html']],
    'register_name' =>['index/api/register_name',['ext'=>'html']],
    'book_insert' =>['index/api/book_insert',['ext'=>'html']],
    'friend'=>['index/api/friend',['ext'=>'html']],
    'pk_data'=>['index/api/pk_data',['ext'=>'html']],
    'friend_search'=>['index/api/friend_search',['ext'=>'html']],
    'task'=>['index/api/task',['ext'=>'html']],
    'task_star'=>['index/api/task_star',['ext'=>'html']],
    'task_list'=>['index/api/task_list',['ext'=>'html']],
    'group_context'=>['index/api/group_context',['ext'=>'html']],
    'group_rank'=>['index/api/group_rank',['ext'=>'html']],
    'group_finial'=>['index/api/group_finial',['ext'=>'html']],
    'group_details'=>['index/api/group_details',['ext'=>'html']],
    'pk_modern'=>['index/api/pk_modern',['ext'=>'html']],
    'pk_know'=>['index/api/pk_know',['ext'=>'html']],
    'group_medal'=>['index/api/group_medal',['ext'=>'html']],
    'group_medal_details'=>['index/api/medal_details',['ext'=>'html']],
    'group_search_tag'=>['index/api/search_tag',['ext'=>'html']],
    'group_search_list'=>['index/api/search_list',['ext'=>'html']],
    'group_main'=>['index/api/group_main',['ext'=>'html']],
    'group_main_rank'=>['index/api/main_rank',['ext'=>'html']],
    'group_board'=>['index/api/group_board',['ext'=>'html']],
    'group_list'=>['index/api/group_list',['ext'=>'html']],
    'group_search'=>['index/api/group_search',['ext'=>'html']],
    'board_send_form'=>['index/api/board_send',['ext'=>'html']],
    'board_praise'=>['index/api/board_praise',['ext'=>'html']],
    'group_day'=>['index/api/group_day',['ext'=>'html']],
    'group_level'=>['index/api/group_level',['ext'=>'html']],
    'group_member'=>['index/api/group_member',['ext'=>'html']],
    'member_status'=>['index/api/member_status',['ext'=>'html']],
    'group_out'=>['index/api/group_out',['ext'=>'html']],
    'group_dismiss'=>['index/api/group_dismiss',['ext'=>'html']],
    'group_avatar'=>['index/api/group_avatar',['ext'=>'html']],
    'group_create'=>['index/api/group_create',['ext'=>'html']],
    'group_star'=>['index/api/group_star',['ext'=>'html']],
    'group_delete'=>['index/api/group_delete',['ext'=>'html']],
    'group_summary'=>['index/api/group_summary',['ext'=>'html']],
    'summary_add'=>['index/api/summary_add',['ext'=>'html']],
    'group_setting'=>['index/api/group_setting',['ext'=>'html']],
    'setting_add'=>['index/api/setting_add',['ext'=>'html']],
    'group_add'=>['index/api/group_add',['ext'=>'html']],
    'group_add_text'=>['index/api/group_add_text',['ext'=>'html']],
    'friend_main'=>['index/api/friend_main',['ext'=>'html']],
    'friend_add'=>['index/api/friend_add',['ext'=>'html']],
    'user_main'=>['index/api/user_main',['ext'=>'html']],
    'user_summary_add'=>['index/api/user_summary_add',['ext'=>'html']],
    'user_share'=>['index/api/user_share',['ext'=>'html']],
    'word_data'=>['index/api/word_data',['ext'=>'html']],
    'user_data'=>['index/api/user_data',['ext'=>'html']],
    'user_friend'=>['index/api/user_friend',['ext'=>'html']],
    'friend_update'=>['index/api/friend_update',['ext'=>'html']],
    'setting_account'=>['index/api/setting_account',['ext'=>'html']],
    'update_name'=>['index/api/update_name',['ext'=>'html']],
    'update_nickname'=>['index/api/update_nickname',['ext'=>'html']],
    'update_pass'=>['index/api/update_pass',['ext'=>'html']],
    'update_phone'=>['index/api/update_phone',['ext'=>'html']],
    'user_money'=>['index/api/user_money',['ext'=>'html']],
    'user_photo'=>['index/api/user_photo',['ext'=>'html']],
    'home_recite'=>['index/api/home_recite',['ext'=>'html']],
    'home_check'=>['index/api/home_check',['ext'=>'html']],
    'home_find'=>['index/api/home_find',['ext'=>'html']],
    'recite_check'=>['index/api/recite_check',['ext'=>'html']],
    'recite_open'=>['index/api/recite_open',['ext'=>'html']],
];




































